In [ ]:
from google.colab import drive

drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

path = "/content/drive/MyDrive/Projekt zaliczeniowy/diabetes_012_health_indicators_BRFSS2015.csv"
df = pd.read_csv(path)

1. Pobranie datasetu z kaggle.com

In [ ]:
df

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

2. Weryfikacja ilości wartości na daną klasę. Można zauważyć dużą dysproporcję każdej z nich

In [ ]:
df['Diabetes_012'].value_counts()

0.0    213703
2.0     35346
1.0      4631
Name: Diabetes_012, dtype: int64

In [ ]:
df1 = df.loc[df['Diabetes_012'] == 0.0]

In [ ]:
df1

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253673,0.0,1.0,0.0,1.0,42.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,14.0,4.0,0.0,1.0,3.0,6.0,8.0
253674,0.0,0.0,0.0,1.0,27.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,6.0,5.0
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0

3. Redukcja ilości wierszy należących do danej klasy, aż do poziomu, w którym każda z nich posiadała taką samą ilość sampli - 4500. Te same metody zastosowano dla każdej z klas.

In [ ]:
N = 249180
df1 = df1.tail(df.shape[0] -N)

df1

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
247978,0.0,1.0,0.0,1.0,29.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,30.0,0.0,0.0,0.0,7.0,6.0,8.0
247979,0.0,0.0,0.0,1.0,20.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,5.0,0.0,0.0,4.0,6.0,8.0
247980,0.0,0.0,0.0,1.0,29.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,4.0,0.0,3.0,0.0,1.0,9.0,5.0,6.0
247981,0.0,0.0,0.0,1.0,20.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,13.0,6.0,8.0
247984,0.0,1.0,1.0,1.0,27.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,12.0,4.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253673,0.0,1.0,0.0,1.0,42.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,14.0,4.0,0.0,1.0,3.0,6.0,8.0
253674,0.0,0.0,0.0,1.0,27.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,3.0,6.0,5.0
253675,0.0,1.0,1.0,1.0,45.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,5.0,0.0,1.0,5.0,6.0,7.0
253677,0.0,0.0,0.0,1.0,28.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,2.0,5.0,2.0
253678,0.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,7.0,5.0,1.0

In [ ]:
df1['Diabetes_012'].value_counts()

0.0    4500
Name: Diabetes_012, dtype: int64

In [ ]:
df2 = df.loc[df['Diabetes_012'] == 2.0]
df2

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
8,2.0,1.0,1.0,1.0,30.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,30.0,30.0,1.0,0.0,9.0,5.0,1.0
10,2.0,0.0,0.0,1.0,25.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,13.0,6.0,8.0
13,2.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,4.0,6.0
17,2.0,0.0,0.0,1.0,23.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,7.0,5.0,6.0
23,2.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,1.0,0.0,0.0,0.0,0.0,13.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253659,2.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
253668,2.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,1.0,1.0,10.0,3.0,6.0
253670,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,15.0,0.0,1.0,0.0,13.0,6.0,4.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [ ]:
M = 30868
df2 = df2.tail(df.shape[1] -M)
df2

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
221345,2.0,1.0,0.0,1.0,33.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,5.0,30.0,21.0,1.0,0.0,8.0,6.0,3.0
221351,2.0,1.0,0.0,1.0,33.0,0.0,1.0,0.0,1.0,0.0,...,1.0,0.0,3.0,0.0,0.0,1.0,1.0,10.0,5.0,6.0
221357,2.0,1.0,1.0,1.0,27.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,13.0,2.0,3.0
221377,2.0,1.0,1.0,1.0,30.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,4.0,5.0,10.0,1.0,0.0,11.0,4.0,1.0
221385,2.0,1.0,0.0,1.0,29.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,1.0,11.0,5.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253659,2.0,0.0,1.0,1.0,37.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,4.0,1.0
253668,2.0,0.0,1.0,1.0,29.0,1.0,0.0,1.0,0.0,1.0,...,1.0,0.0,2.0,0.0,0.0,1.0,1.0,10.0,3.0,6.0
253670,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,5.0,15.0,0.0,1.0,0.0,13.0,6.0,4.0
253676,2.0,1.0,1.0,1.0,18.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,4.0,0.0,0.0,1.0,0.0,11.0,2.0,4.0
253679,2.0,1.0,1.0,1.0,25.0,0.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,9.0,6.0,2.0

In [ ]:
df2['Diabetes_012'].value_counts()

2.0    4500
Name: Diabetes_012, dtype: int64

In [ ]:
df3 = df.loc[df['Diabetes_012'] == 1.0]
df3

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
64,1.0,1.0,1.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,1.0,4.0,30.0,30.0,1.0,0.0,10.0,4.0,3.0
81,1.0,1.0,1.0,1.0,33.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,3.0,0.0,0.0,1.0,7.0,4.0,7.0
193,1.0,1.0,1.0,1.0,34.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,7.0,4.0,8.0
236,1.0,1.0,1.0,1.0,33.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,5.0,30.0,30.0,1.0,0.0,12.0,6.0,6.0
275,1.0,1.0,1.0,1.0,32.0,1.0,1.0,0.0,1.0,0.0,...,1.0,0.0,5.0,0.0,30.0,1.0,1.0,8.0,5.0,7.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253528,1.0,1.0,0.0,1.0,34.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,6.0,0.0,0.0,4.0,5.0,4.0
253529,1.0,1.0,0.0,1.0,32.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,2.0,0.0,1.0,9.0,6.0,7.0
253566,1.0,0.0,0.0,1.0,24.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,10.0,6.0,4.0
253664,1.0,0.0,1.0,1.0,29.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,6.0,6.0,4.0
253666,1.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,15.0,0.0,0.0,6.0,5.0,2.0

In [ ]:
O = 153
df3 = df3.tail(df.shape[1] -O)
df3

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
7077,1.0,0.0,0.0,1.0,38.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,6.0,4.0
7235,1.0,1.0,0.0,1.0,32.0,1.0,1.0,1.0,0.0,0.0,...,1.0,0.0,4.0,30.0,10.0,1.0,1.0,11.0,6.0,6.0
7308,1.0,1.0,1.0,1.0,25.0,1.0,0.0,1.0,1.0,0.0,...,1.0,0.0,5.0,0.0,30.0,1.0,1.0,13.0,4.0,2.0
7405,1.0,0.0,1.0,1.0,19.0,1.0,0.0,1.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,13.0,6.0,8.0
7431,1.0,1.0,1.0,1.0,30.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,12.0,5.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
253528,1.0,1.0,0.0,1.0,34.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,6.0,0.0,0.0,4.0,5.0,4.0
253529,1.0,1.0,0.0,1.0,32.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,2.0,0.0,1.0,9.0,6.0,7.0
253566,1.0,0.0,0.0,1.0,24.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,10.0,6.0,4.0
253664,1.0,0.0,1.0,1.0,29.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,6.0,6.0,4.0
253666,1.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,15.0,0.0,0.0,6.0,5.0,2.0

In [ ]:
df3['Diabetes_012'].value_counts()

1.0    4500
Name: Diabetes_012, dtype: int64

4. Połączenie 3 zredukowanych Dataframów każdej z klasy do wspólnego Datasetu (df4)

In [ ]:
dfs = [df1, df2, df3]
df4 = pd.concat([df.squeeze() for df in dfs], ignore_index=True)

df4

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,0.0,1.0,29.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,30.0,0.0,0.0,0.0,7.0,6.0,8.0
1,0.0,0.0,0.0,1.0,20.0,0.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,5.0,0.0,0.0,4.0,6.0,8.0
2,0.0,0.0,0.0,1.0,29.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,4.0,0.0,3.0,0.0,1.0,9.0,5.0,6.0
3,0.0,0.0,0.0,1.0,20.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,13.0,6.0,8.0
4,0.0,1.0,1.0,1.0,27.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,0.0,0.0,1.0,12.0,4.0,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13495,1.0,1.0,0.0,1.0,34.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,3.0,0.0,6.0,0.0,0.0,4.0,5.0,4.0
13496,1.0,1.0,0.0,1.0,32.0,1.0,0.0,0.0,1.0,0.0,...,1.0,0.0,2.0,0.0,2.0,0.0,1.0,9.0,6.0,7.0
13497,1.0,0.0,0.0,1.0,24.0,0.0,0.0,1.0,0.0,1.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,10.0,6.0,4.0
13498,1.0,0.0,1.0,1.0,29.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,3.0,0.0,0.0,0.0,0.0,6.0,6.0,4.0
13499,1.0,1.0,0.0,1.0,23.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,0.0,15.0,0.0,0.0,6.0,5.0,2.0

5. Uzyskanie równej ilości sampli dla każdej z klas

In [ ]:
df4['Diabetes_012'].value_counts()

0.0    4500
2.0    4500
1.0    4500
Name: Diabetes_012, dtype: int64

6. Randomizacja sampli

In [ ]:
from sklearn.utils import shuffle
df4 = shuffle(df4)

In [ ]:
df4

,Diabetes_012,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
6573,2.0,1.0,1.0,1.0,28.0,1.0,0.0,0.0,0.0,1.0,...,1.0,0.0,3.0,30.0,30.0,0.0,1.0,9.0,4.0,1.0
2628,0.0,1.0,1.0,1.0,29.0,0.0,0.0,0.0,1.0,1.0,...,0.0,0.0,1.0,7.0,0.0,0.0,0.0,8.0,4.0,2.0
6943,2.0,1.0,1.0,1.0,35.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,2.0,5.0,2.0,0.0,0.0,10.0,4.0,6.0
3701,0.0,1.0,1.0,1.0,30.0,0.0,0.0,0.0,1.0,0.0,...,1.0,1.0,4.0,30.0,0.0,0.0,0.0,10.0,6.0,2.0
2210,0.0,0.0,1.0,1.0,26.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,4.0,5.0,6.0,0.0,0.0,8.0,2.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5708,2.0,1.0,1.0,1.0,33.0,1.0,0.0,0.0,1.0,1.0,...,1.0,0.0,4.0,5.0,7.0,1.0,1.0,10.0,5.0,8.0
2424,0.0,1.0,1.0,1.0,21.0,0.0,0.0,0.0,0.0,1.0,...,1.0,0.0,4.0,0.0,30.0,0.0,0.0,11.0,4.0,3.0
7811,2.0,1.0,1.0,1.0,24.0,0.0,1.0,0.0,0.0,1.0,...,1.0,0.0,4.0,0.0,5.0,1.0,1.0,13.0,6.0,8.0
12599,1.0,1.0,0.0,1.0,32.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,4.0,0.0,0.0,0.0,0.0,6.0,6.0,1.0
5460,2.0,0.0,1.0,1.0,32.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,4.0,30.0,15.0,0.0,0.0,8.0,4.0,5.0

7. Exportowanie zedytowanego datasetu zawierającego 13500 sampli do pliku .csv, w celu sprawdzenia najlepiej pasujących modeli uczenia maszynowego przed przygotwaniem własnego modelu

In [ ]:
from google.colab import files

df4.to_csv('diabetes.csv', encoding = 'utf-8-sig') 
files.download('diabetes.csv')